#!/bin/bash
set -e

login_user=`/usr/bin/stat -f%Su /dev/console`
wubivoice_app_root="${DSTROOT}/WubiVoice.app"
wubivoice_executable="${wubivoice_app_root}/Contents/MacOS/WubiVoice"
rime_package_installer="${wubivoice_app_root}/Contents/MacOS/rime-install"
rime_shared_data_path="${wubivoice_app_root}/Contents/SharedSupport"

/usr/bin/sudo -u "${login_user}" /usr/bin/killall WubiVoice > /dev/null || true

"${wubivoice_executable}" --register-input-source

if [ -z "${RIME_NO_PREBUILD}" ]; then
    pushd "${rime_shared_data_path}" > /dev/null
    "${wubivoice_executable}" --build
    popd > /dev/null
fi && (
    /usr/bin/sudo -u "${login_user}" "${wubivoice_executable}" --enable-input-source
    /usr/bin/sudo -u "${login_user}" "${wubivoice_executable}" --select-input-source
)
